config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|it/ do
    resources :events, only: %i[index show]
    resources :happenings, only: %i[index show] do
      get :calendar, on: :collection
    end
    resources :tickets, except: %i[edit update]

    namespace "editor" do
      root "events#index"
      resources :events
      resources :happenings
      resources :tickets, except: %i[show]
      resources :users, only: %i[index show]
    end

    namespace "admin" do
      root "users#index"
      resources :users, only: %i[index edit update]
      resources :groups, except: %i[show]
      resources :templates
    end
  end
  if RAILS_DEVISE_OMNIAUTHABLE
    devise_for :users, prefix: "auth", controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  else
    devise_for :users, prefix: "auth"
  end
  unless RAILS_DEVISE_DATABASE_AUTHENTICATABLE
    devise_scope :user do
      get "sign_in", to: "devise/sessions#new", as:  :new_user_session
      delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
    end
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "/:locale" => "events#index"
  root to: redirect("/it/events") # 'events#index'
end

app/models/group.rb
# frozen_string_literal: true

# This model manage the group
# === Relations
# has many {Event}
# has and belongs to many {User}
# === Validates
# * presence of {title}
# @!attribute [rw] title
#   @return [String] group title
class Group < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :events, dependent: :restrict_with_error

  validates :title, presence: true
end

app/controllers/admin/groups_controller.rb
# frozen_string_literal: true

module Admin
  # This controller manage {Group} model for admin {User}
  class GroupsController < Admin::ApplicationController
    before_action :set_group, only: %i[edit update destroy]
    before_action :set_users, only: %i[new create edit update]

    # GET /admin/groups
    def index
      @text = [ "title ilike :text", { text: "%#{filter_params[:text]}%" } ] if filter_params[:text].present?
      @pagy, @groups = pagy(Group.all.where(@text))
    end

    # GET /admin/groups/new
    def new
      @group = Group.new
      render action: "edit"
    end

    # GET /admin/groups/1/edit
    def edit
      @users = User.editors.pluck :email, :id
    end

    # POST /admin/groups
    def create
      @group = Group.new(group_params)
      set_users

      if @group.save
        @status = { success: "Gruppo creato" }
        redirect_to admin_groups_path
      else
        @status = { error: "Creazione gruppo fallita" }
        render action: "edit"
      end
    end

    # PATCH/PUT /admin/groups/1
    def update
      @users = @group.users.pluck :email, :id
      if @group.update(group_params)
        @status = { success: "Gruppo aggiornato" }
        redirect_to admin_groups_path
      else
        @status = { error: "Aggiornamento gruppo fallito" }
        render :edit
      end
    end

    # DELETE /admin/groups/1
    def destroy
      @group.destroy
      redirect_to admin_groups_path, notice: "Group was successfully destroyed."
    end

    private

    # Set {Group} when needed
    def set_group
      @group = Group.find(params[:id])
    end

    # preset users value
    def set_users
    @users = User.editors.pluck :email, :id
    end

    # filter params for search groups
    def filter_params
      params.fetch(:filter, {}).permit(:text)
    end

    # Filter params for create/change a {Ticket} istance
    def group_params
      params.require(:group).permit(:title, user_ids: [])
    end
  end
end

app/views/admin/groups/edit.html.haml
%turbo-frame#yield
  %h3.title.has-text-centered
    %i.fas.fa-users
    Gestione
    = t 'activerecord.models.group.other'
  .columns
    %aside.column.is-3
      = render Layout::SearchComponent.new(url: admin_groups_path, turbo_frame: 'groups', date_range: false)
      = link_to icon_text('fas fa-fw', 'Nuovo gruppo'), new_admin_group_path, class: 'is-success button is-fullwidth', data: {turbo_frame: 'groups'}
    .column
      %turbo-frame#groups
        .box.mb-2
          = form_with(model: [:admin, @group]) do |form|
            .field
              = form.label :title
              .control.has-icons-left
                = form.text_field :title, class: 'input'
                .icon.is-small.is-left
                  %i.fas.fa-heading
              %p.help.is-danger= @group.errors[:title].join(' - ')
            .field
              = form.label :user_ids
              .control.has-icons-left
                = form.select :user_ids, @users, {}, {multiple: true, data: {controller: 'slim', slim_target: 'editor'}}
                %p.help.is-danger= @group.errors.messages[:user].join(' - ')

            .has-text-centered
              = form.button fas_icon('save', text: 'Salva'), class: 'button is-success'
              = link_to icon_text('fas fa-chevron-left', 'Indietro'), admin_groups_path, class: 'button is-link'
              = link_to icon_text('fas fa-trash', 'Elimina'), admin_group_path(@group), data: {turbo_method: :delete, turbo_confirm: 'Attenzione, se presenti degli eventi collegati il gruppo non verrà eliminato. proseguire?'}, class: 'button is-warning' if @group.persisted?

app/views/admin/groups/index.html.haml
%turbo-frame#yield
  %h3.title.has-text-centered
    %i.fas.fa-users
    Amministrazione
    = t 'activerecord.models.group.other'
  .columns
    %aside.column.is-3
      = render Layout::SearchComponent.new(url: admin_groups_path, turbo_frame: 'groups', date_range: false)
      = link_to icon_text('fas fa-fw', 'Nuovo gruppo'), new_admin_group_path, class: 'is-success button is-fullwidth', data: {turbo_frame: 'groups'}
    .column= render Layout::ListComponent.new(component: Groups::GroupComponent, elements: @groups, id: 'groups', pages: @pagy)