config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|it/ do
    resources :events, only: %i[index show]
    resources :happenings, only: %i[index show] do
      get :calendar, on: :collection
    end
    resources :tickets, except: %i[edit update]

    namespace "editor" do
      root "events#index"
      resources :events
      resources :happenings
      resources :tickets, except: %i[show]
      resources :users, only: %i[index show]
    end

    namespace "admin" do
      root "users#index"
      resources :users, only: %i[index edit update]
      resources :groups, except: %i[show]
      resources :templates
    end
  end
  if RAILS_DEVISE_OMNIAUTHABLE
    devise_for :users, prefix: "auth", controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  else
    devise_for :users, prefix: "auth"
  end
  unless RAILS_DEVISE_DATABASE_AUTHENTICATABLE
    devise_scope :user do
      get "sign_in", to: "devise/sessions#new", as:  :new_user_session
      delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
    end
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "/:locale" => "events#index"
  root to: redirect("/it/events") # 'events#index'
end

app/controllers/editor/application_controller.rb
# frozen_string_literal: true

module Editor
  # This controller contain the methods shared for all editor controller
  class ApplicationController < ApplicationController
    before_action :authenticate_editor!

    private

    # deny access unless current_user is an editor
    def authenticate_editor!
      access_denied! unless user_signed_in? && (current_user.editor? || current_user.admin?)
    end
  end
end

app/controllers/editor/events_controller.rb
# frozen_string_literal: true

module Editor
  # This controller manage {Event} model for editors
  class EventsController < Editor::ApplicationController
    before_action :set_groups
    before_action :set_event, only: %i[show edit update destroy]

    # GET /editor/events
    def index
      @categories = @groups.pluck :title, :id
      from     = filter_params[:from]
      to       = filter_params[:to]
      group_id = @groups.exists?(filter_params[:category]) ? filter_params[:category] : @groups.pluck(:id)
      text     = filter_params[:text]
      @pagy, @events = pagy(Event.searchable(from:, to:, group_id:, text:, editor: true, reserved: true), items: 6)
    end

    # GET /editor/events/:id
    def show; end

    # GET /editor/events/new
    def new
      @event = Event.new
    end

    # GET /editor/events/:id/edit
    def edit; end

    # POST /editor/events
    def create
      @event = Event.new(event_params)
      if @event.save
        @status = { success: "Evento creato" }
        redirect_to editor_event_path(@event)
      else
        @status = { error: "ERRORE - Evento non creato. Verifica gli errori." }
        render action: :new
      end
    end

    # PATCH/PUT /editor/events/:id
    def update
      if @event.update(event_params)
        @status = { success: "Evento Aggiornato" }
        render action: :show
      else
        @status = { error: "ERRORE - Evento non aggiornato. Verifica gli errori." }
        render :edit
      end
    end

    # DELETE /editor/events/:id
    def destroy
      if @event.destroy
        @status = { success: "Evento eliminato" }
        redirect_to editor_events_path
      else
        @status = { error: "ERRORE - Evento non eliminato. Verifica gli errori." }
        render action: :edit
      end
    end

    private

    # set @event for current user when needed
    def set_event
      @event = Event.find_by(id: params[:id], group: @groups)
      @scope = @event.id
    end

    def set_groups
      @groups = current_user.groups
    end

    # Filter params for search a {Event}
    def filter_params
      params.fetch(:filter, {}).permit(:category, :from, :text, :to)
    end

    # Filter params for set a {Event}
    def event_params
      params.require(:event).permit(:tickets_frequency, :title, :group_id, :body, :start_on, :stop_on, :pinned, :image, :where, :single, :reserved)
    end
  end
end

app/controllers/editor/happenings_controller.rb
# frozen_string_literal: true

module Editor
  # This controller manafe {Happening} model for editors
  class HappeningsController < Editor::ApplicationController
    before_action :set_groups
    before_action :set_happening, only: %i[show edit update destroy]

    # GET /editor/events/:event_id/happenings
    def index
      request.format = filter_params[:format].to_sym if filter_params[:format].present?
      @categories = Group.pluck :title, :id
      @scope   = filter_params[:scope]
      from     = filter_params[:from]
      to       = filter_params[:to]
      event_id = filter_params[:scope]
      group_id = @groups.exists?(filter_params[:category]) ? filter_params[:category] : @groups.pluck(:id)
      text     = filter_params[:text]
      soldout  = filter_params[:soldout]
      searchable = Happening.searchable(from:, to:, event_id:, group_id:, text:, soldout:, reserved: true)
      respond_to do |format|
        format.html { @pagy, @happenings = pagy(searchable, items: 6) }
        format.csv { @happenings = searchable.includes(:questions, tickets: [ :answers, :user ]) }
        format.pdf { @happenings = searchable.includes(:questions, tickets: [ :answers, :user ]) }
      end
    end

    # GET /editor/events/:event_id/happenings/:id
    def show
      respond_to do |format|
        format.html { }
        format.csv { }
        format.pdf { }
      end
    end

    # GET /editor/events/event_id/happenings/new
    def new
      @event = Event.find_by(id: params[:event_id], group: @groups)
      @happening = @event.happenings.new
      @templates = Template.pluck :title, :id
    end

    # GET /editor/events/:event_id/happenings/:id/edit
    def edit
      @happening.questions.new
    end

    # POST /editor/happenings
    def create
      @event = Event.find_by(id: massive_create_params[:event_id], group: @groups)
      @happenings = @event.happenings.massive_create(**massive_create_params.to_h.to_options)
      @happening = @happenings.first

      if @happening.save
        render "editor/events/show"
      else
        render :new
      end
    end

    # PATCH/PUT /editor/events/:event_id/happenings/:id
    def update
      if @happening.update(happening_params)
        render action: :show
      else
        render :edit
      end
    end

    # DELETE /editor/events/:event_id/happenings/:id
    def destroy
      @happening.destroy
      redirect_to editor_event_path(@happening.event)
    end

    private

    def set_groups
      @groups = current_user.groups
    end

    # Set @happening when needed
    def set_happening
      @happening = Happening.includes(:event).where(event: { group: current_user.groups }).find(params[:id])
      @event = @happening.event
    end

    # Filter params for set an {Happening}
    def happening_params
      params.require(:happening).permit(:title, :image, :event_id, :max_tickets, :max_tickets_for_user, :start_at, :start_sale_at, :stop_sale_at, questions_attributes: [ :id, :title, :category, :mandatory, :weight, :_destroy ])
    end

    def massive_create_params
      params.require(:happening).permit(:title, :image, :event_id, :max_tickets, :max_tickets_for_user, :from, :to, :start_sale_before, :stop_sale_before, :template_id, repeat_in: [], minutes: [])
    end


    # Filter params for search an {Happening}
    def filter_params
      params.fetch(:filter, {}).permit(:from, :category, :scope, :text, :to, :soldout, :format)
    end
  end
end

app/controllers/editor/tickets_controller.rb
# frozen_string_literal: true

module Editor
  # This controller manage {Ticket} model for editors
  class TicketsController < Editor::ApplicationController
    require "csv"
    before_action :check_happening, only: %i[create update]
    before_action :set_ticket, only: %i[edit update destroy]

    # GET /editor/tickets
    def index
      @happening = Happening.find(filter_params[:scope]) if filter_params[:scope].present?
      search = {}
      search[:happening] = { start_at: ((filter_params[:from].try(:to_date) || Date.today)..filter_params[:to].try(:to_date).try(:end_of_day)) }
      search[:happening_id] = @happening.id if @happening.present?
      search[:user_id] = filter_params[:category] if filter_params[:category].present?
      @text = [ "events.title ilike :text or users.email ilike :text", { text: "%#{filter_params[:text]}%" } ] if filter_params[:text].present?
      searchable = Ticket.includes(happening: [ :event ]).where(search).where(@text)
      respond_to do |format|
        format.html { @pagy, @tickets = pagy(searchable, items: 10) }
        format.csv { @tickets = searchable }
        format.pdf { @tickets = searchable }
      end
    end

    # GET /editor/events/:event_id/happenings/:happening_id/tickets/new
    def new
      @ticket = Ticket.new(happening_id: happening_id(filter_params[:happening_id]))
      @users = User.pluck :email, :id
    end

    # GET /editor/events/:event_id/happenings/:happening_id/tickets/:id/edit
    def edit
      @users = User.pluck :email, :id
    end

    # POST /editor/events/:event_id/happenings/:happening_id/tickets/
    def create
      @ticket = Ticket.new(ticket_params)
      @ticket.by_editor = true
      if @ticket.save
        broadcast_action_to "editor:happening_#{@ticket.happening_id}", action: :prepend, target: "editor_tickets",
                                                                        locals: { ticket: self }, partial: "editor/tickets/ticket"
        render turbo_stream: [
          turbo_stream.replace("editor_ticket_#{@ticket.id}", partial: "ticket", locals: { ticlet: @ticket }),
          turbo_stream.replace("modal", partial: "modal_empty")
        ]

        render "empty_modal"
      else
        @status = { error: "Creatione prenotazione fallita" }
        render action: "new"
      end
    end

    # PATCH/PUT /editor/events/:event_id/happenings/:happening_id/tickets/:id
    def update
      if @ticket.update(ticket_params.merge(by_editor: true))
        render partial: "modal_empty"
      else
        render partial: "form", locals: { ticket: @ticket, happening: @happening, event: @event }
      end
    end

    # DELETE /editor/events/:event_id/happenings/:happening_id/tickets/:id
    def destroy
      @ticket.destroy
    end

    private

    def check_happening
      access_denied! unless event_ids.include?(Happening.find(ticket_params[:happening_id]).event_id)
    end

    # set @event before any action
    def event_ids
      current_user.events.pluck(:id)
    end

    # Set @happening before any action
    def happening_id(value)
      Happening.find_by(id: value, event_id: event_ids).id
    end

    # Set ticket when needed
    def set_ticket
      @ticket = Ticket.includes(:happening).find(params[:id])
      access_denied! unless event_ids.include?(@ticket.happening.event_id)
    end

    # Filter params for set a ticket
    def ticket_params
      params.require(:ticket).permit(:happening_id, :user_id, :seats)
    end

    # Filter params for search an {Ticket}
    def filter_params
      params.fetch(:filter, {}).permit(:category, :from, :scope, :text, :to)
    end
  end
end

app/controllers/editor/users_controller.rb
# frozen_string_literal: true

module Editor
  # This controller manage {User} model for editors
  class UsersController < Editor::ApplicationController
    before_action :set_user, only: %i[show tickets]
    # GET /editor/users
    def index
      @pagy, @users = pagy User.searchable(**filter_params.to_h)
    end

    # GET /editor/users/list
    def list
      if filter_params[:text].present?
        @text = [ "email ilike :text or email ilike :text",
                 { text: "%#{filter_params[:text]}%" } ]
      end
      @pagy, @users = pagy(User.where(@text).where(options))
    end

    # GET /editor/users/:id
    def show
      @categories = [ [ @user.email, @user.id ] ]
    end

    # GET /editor/users/:id/tickets
    def tickets
      @text = [ "events.title ilike :string", { string: "%#{filter_params[:text]}%" } ] if filter_params[:text].present?
      if current_user.admin?
        @pagy, @tickets = pagy(@user.tickets.joins(happening: [ :event ]).where(@text), items: 6)
      else
        @pagy, @tickets = pagy(
          @user.tickets.joins(happening: [ :event ]).where(happening: { event: @current_user.events }).where(@text),
          items: 6
        )
      end
    end

    private

    # Set @user for some method
    def set_user
      @user = User.find(params[:id])
    end

    # Filter params for search a {Event}
    def filter_params
      params.fetch(:filter, {}).permit(:text, :admin, :editor)
    end
  end
end

app/controllers/happenings_controller.rb
# frozen_string_literal: true

# this controller manage the {User} views for {Happening} model.
class HappeningsController < ApplicationController
  # GET /event/:event_id/happenings
  # show a paginate list of {Happening}
  def index
    @categories = Group.pluck :title, :id
    @scope   = filter_params[:scope]
    from     = filter_params[:from]
    to       = filter_params[:to]
    event_id = filter_params[:scope]
    group_id = filter_params[:category]
    text     = filter_params[:text]
    soldout  = filter_params[:soldout]
    @pagy, @happenings = pagy(Happening.searchable(from:, to:, event_id:, group_id:, text:, soldout:, reserved: include_reserved?), items: 6)
  end

  # GET /event/:event_id/happenings/:id
  # Show detail of happening and a form to prenotate a ticket
  def show
    @happening = Happening.includes(:event).find(params[:id])
    @event = @happening.event
    access_denied! if @event.reserved? && !include_reserved?
  end

  # GET /happenings/calendar
  def calendar
    @month = filter_params[:month].to_i
    @day = Date.today.at_beginning_of_month + @month.month
    @category = filter_params[:category]
    @scope = filter_params[:scope]
    @from = @day - @day.wday.days
    @to = @from + 41
    @days = Happening.highlight_dates(from: @from, to: @to, group_id: @category, event_id: @scope, reserved: include_reserved?).join(" ")
    # start = Date.today.at_beginning_of_month
    # @range = (start...start.+(12.month)).step(1.month)
  end

  private

  # filter params for search {Happening}
  def filter_params
    params.fetch(:filter, {}).permit(:category, :from, :scope, :text, :to, :soldout, :month)
  end
end

app/views/editor/happenings/edit.html.haml
%turbo-frame#yield
  %turbo-frame#tickets
    %h5.title.is-size-5.has-text-centered
      %i.fas.fa-calendar-alt
      Modifica evento

    %turbo-frame#happening
      .box
        = form_with(model: [:editor, @happening], data: {turbo_frame: 'happening', controller: 'nested'}) do |form|
          = form.hidden_field :event_id, value: @event.id
          .field.is-horizontal
            .field-body
              .field
                = form.label :title
                .control.has-icons-left
                  = form.text_field :title, class: 'input'
                  .icon.is-small.is-left
                    %i.fas.fa-heading
            %p.help.is-danger= @happening.errors[:title].join(' - ')
          .field
            = form.label :image
            .control.has-icons-left
              = form.file_field :image, class: 'input'
              .icon.is-small.is-left
                %i.fas.fa-image
            %p.help.is-danger= @happening.errors[:image].join(' - ')
          .field.is-horizontal
            .field-body
              .field
                = form.label :start_at
                .control.has-icons-left
                  = form.datetime_field :start_at, class: 'input'
                  %span.icon.is-small.is-left
                    %i.fas.fa-calendar-day
                %p.help.is-danger= @happening.errors[:start_at].join(' - ')
              .field
                = form.label :start_sale_at
                .control.has-icons-left
                  = form.datetime_field :start_sale_at, class: 'input'
                  %span.icon.is-small.is-left
                    %i.fas.fa-calendar-day
                %p.help.is-danger= @happening.errors[:start_sale_at].join(' - ')
              .field
                = form.label :stop_sale_at
                .control.has-icons-left
                  = form.datetime_field :stop_sale_at, class: 'input'
                  %span.icon.is-small.is-left
                    %i.fas.fa-calendar-day
                %p.help.is-danger= @happening.errors[:stop_sale_at].join(' - ')

          .field.is-horizontal
            .field-body
              .field
                = form.label :max_tickets
                .control.has-icons-left
                  = form.number_field :max_tickets, class: 'input'
                  %span.icon.is-small.is-left
                    %i.fas.fa-chair
                %p.help.is-danger= @happening.errors[:max_tickets].join(' - ')
              .field
                = form.label :max_tickets_for_user
                .control.has-icons-left
                  = form.number_field :max_tickets_for_user, class: 'input'
                  %span.icon.is-small.is-left
                    %i.fas.fa-chair
                %p.help.is-danger= @happening.errors[:max_tickets_for_user].join(' - ')
          .divider Domande
          .div{data: {nested_target: 'content'}}
            = form.fields_for :questions do |sub_form|
              - if sub_form.object.persisted?
                = render Editor::Questions::SubFormComponent.new form: sub_form
              - else
                %template{data: {nested_target: 'template'}}= render Editor::Questions::SubFormComponent.new form: sub_form
          .buttons.has-text-centered
            = form.button fas_icon('save', text: t('site.generic.save')), class: 'button is-success'
            %a.button.is-link{href: editor_happening_path(@happening)}= fas_icon 'chevron-left', text: 'Indietro'
            = link_to fas_icon('trash', text: 'Elimina'), editor_happening_path(@happening), class: 'button is-warning', data: {turbo_confirm: 'Attenzione la data e tutte le prenotazioni saranno eliminate, confermi?', turbo_method: :delete, turbo_frame: 'yield'}
            %a.is-success.button{data: {action: 'nested#add'}}= fas_icon 'plus', text: 'Aggiungi domanda'

app/views/editor/happenings/index.csv.erb
<%=
  CSV.generate(headers: true) do |csv|
    csv << [ "Date","Happening title","Name","Surname","Email","Question","Answer" ]
    @happenings.each do |happening|
      happening.tickets.each do |ticket|
        if ticket.answers.present?
          csv << [l(happening.start_at, format: :long), happening.title, ticket.user.name, ticket.user.surname, ticket.user.email]
          ticket.answers.includes(:question).order("questions.weight desc").each do |answer|
            csv << ["", "", "", "", "", answer.question.title, answer.value]
          end
        else
          csv << [I18n.l(happening.start_at), happening.title, ticket.user.name, ticket.user.surname, ticket.user.email]
        end
      end
    end
  end .html_safe
%>

app/views/editor/happenings/index.html.haml
%turbo-frame#yield
  %h3.title.has-text-centered
    %i.fas.fa-calendar-day
    Gestione
    = t 'activerecord.models.happening.other'
  .columns
    %aside.column.is-3= render Layout::SearchComponent.new(url: editor_happenings_path, turbo_frame: 'happenings', scope: @scopei, categories: @categories, editor: true, soldout: true, export: true)
    .column= render Layout::ListBoxedComponent.new(component: Happenings::HappeningComponent, elements: @happenings, id: 'happenings', pages: @pagy, turbo_frame: 'yield', url: :editor_happening_path)

app/views/editor/happenings/new.html.haml
%turbo-frame#yield
  %h3.title.has-text-centered
    %i.fas.fa-tools
    = @event.title
  .columns
    %aside.column.is-3
      .block
        %figure.image= image_tag @event.image_url(:aside)
    .column
      %turbo-frame#event= render Events::InfoboxComponent.new(event: @event, editor: true)
      .divider= icon_text 'fas fa-calendar-day', "nuova #{t('activerecord.models.happening.one')}"
      %turbo-frame#happening
        .box
          = form_with(model: [:editor, @happening], data: {turbo_frame: 'yield'}) do |form|
            = form.hidden_field :event_id, value: @event.id
            .field
              = form.label :title
              .control.has-icons-left
                = form.text_field :title, class: 'input'
                .icon.is-small.is-left
                  %i.fas.fa-heading
              %p.help.is-danger= @happening.errors[:title].join(' - ')
            .field
              = form.label :image
              .control.has-icons-left
                = form.file_field :image, class: 'input'
                .icon.is-small.is-left
                  %i.fas.fa-image
              %p.help.is-danger= @happening.errors[:image].join(' - ')
            .field.is-horizontal
              .field-body
                .field
                  = form.label :from
                  .control.has-icons-left
                    = form.date_field :from, class: 'input'
                    %span.icon.is-small.is-left
                      %i.fas.fa-calendar-day
                .field
                  = form.label :to
                  .control.has-icons-left
                    = form.date_field :to, class: 'input'
                    %span.icon.is-small.is-left
                      %i.fas.fa-calendar-day
                .field
                  = form.label :start_sale_before
                  .control.has-icons-left
                    = form.number_field :start_sale_before, class: 'input'
                    %span.icon.is-small.is-left
                      %i.fas.fa-calendar-day
                .field
                  = form.label :stop_sale_before
                  .control.has-icons-left
                    = form.number_field :stop_sale_before, class: 'input'
                    %span.icon.is-small.is-left
                      %i.fas.fa-calendar-day
            .field.is-horizontal
              .field-body
                .field
                  = form.label :max_tickets
                  .control.has-icons-left
                    = form.number_field :max_tickets, class: 'input'
                    %span.icon.is-small.is-left
                      %i.fas.fa-chair
                  %p.help.is-danger= @happening.errors[:max_tickets].join(' - ')
                .field
                  = form.label :max_tickets_for_user
                  .control.has-icons-left
                    = form.number_field :max_tickets_for_user, class: 'input'
                    %span.icon.is-small.is-left
                      %i.fas.fa-chair
                  %p.help.is-danger= @happening.errors[:max_tickets_for_user].join(' - ')
            .field.is-horizontal
              .field-body
                .field
                  = form.label :repeat_in
                  = form.select :repeat_in, [['lun',1],['mar',2],['mer',3],['gio',4],['ven',5],['sab',6],['dom',0]], {}, multiple: true, data: {controller: 'slim', target: 'slim.simple'}
                  %p.help.is-danger= @happening.errors[:repeat_in].join(' - ')
                .field
                  = form.label :minutes
                  = form.select :minutes, (0..1439).step(30).map {|n| [(Date.today + n.minutes).strftime("%H:%M"), n.to_s] }, {}, multiple: true, data: {controller: 'slim', target: 'slim.simple'}
                  %p.help.is-danger= @happening.errors[:repeat_in].join(' - ')
            .field
              = form.label :template_id
              = form.select :template_id, @templates, {include_blank: true}, data: {controller: 'slim', target: 'slim.simple'}

            .buttons.has-text-centered
              = form.button fas_icon('save', text: t('site.generic.save')), class: 'button is-success'
              %a.button.is-link{href: editor_event_path(@event), data: {turbo_frame: 'yield'}}= fas_icon 'chevron-left', text: 'Indietro'

app/views/editor/happenings/show.csv.erb
<%= 
  CSV.generate(headers: true) do |csv|
    csv << [ "Email" ] + @happening.questions.pluck(:title)
    @happening.tickets.includes(:user, answers: [ :question ]).all.each do |ticket|
      csv << [ ticket.user.email ] + ticket.answers.includes(:question).order("questions.weight desc").map(&:value)
    end
  end
%>

app/views/editor/happenings/show.html.haml
%turbo-frame#yield
  %h3.title.has-text-centered
    %i.fas.fa-tools
    = @event.title
  .columns
    %aside.column.is-3
      .block
        %figure.image= image_tag @happening.image_url(:aside)
      = render Layout::SearchComponent.new(url: editor_tickets_path, turbo_frame: 'tickets', categories: @categories, scope: @event.id, date_range: false, export: true)
    .column
      %turbo-frame#event= render Events::InfoboxComponent.new(event: @event, editor: true)
      .divider= icon_text 'fas fa-calendar-day', t('activerecord.models.happening.other')
      %turbo-frame#happenings
        = render Editor::Happenings::DetailComponent.new(happening: @happening)
      .divider= icon_text 'fas fa-ticket-simple', 'Prenotazioni'
      %turbo-frame#tickets{src: editor_tickets_path(filter: {scope: @happening.id})}
      = turbo_stream_from "editor:happening_#{@happening.id}"