config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|it/ do
    resources :events, only: %i[index show]
    resources :happenings, only: %i[index show] do
      get :calendar, on: :collection
    end
    resources :tickets, except: %i[edit update]

    namespace "editor" do
      root "events#index"
      resources :events
      resources :happenings
      resources :tickets, except: %i[show]
      resources :users, only: %i[index show]
    end

    namespace "admin" do
      root "users#index"
      resources :users, only: %i[index edit update]
      resources :groups, except: %i[show]
      resources :templates
    end
  end
  if RAILS_DEVISE_OMNIAUTHABLE
    devise_for :users, prefix: "auth", controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  else
    devise_for :users, prefix: "auth"
  end
  unless RAILS_DEVISE_DATABASE_AUTHENTICATABLE
    devise_scope :user do
      get "sign_in", to: "devise/sessions#new", as:  :new_user_session
      delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
    end
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "/:locale" => "events#index"
  root to: redirect("/it/events") # 'events#index'
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

module Admin
  # This controller contain the methods shared for all admin controller
  class ApplicationController < ApplicationController
    before_action :authenticate_admin!

    private

    # deny access unless current_user is an editor
    def authenticate_admin!
      access_denied! unless user_signed_in? && current_user.admin?
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# This controller contain the methods shared for all controller
class ApplicationController < ActionController::Base
  include Pagy::Method
  around_action :switch_locale
  before_action :authenticate_user! if ENV.fetch("RAILS_RESTRICTED") { false }

  def default_url_options
    { locale: I18n.locale }
  end

  # rescue_from ActiveRecord::RecordNotFound do
  #   record_not_found!
  # end

  unless RAILS_DEVISE_DATABASE_AUTHENTICATABLE
    def new_session_path(scope)
      new_user_session_path
    end
  end

  private

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  # Render 404 page and stop the work
  # @return [nil]
  def record_not_found!
    render partial: "errors/404", status: :not_found and return
  end

  # Render 401 page and stop the work
  # @return [nil]
  def access_denied!
    render "errors/401", status: :unauthorized and return
  end

  def set_turbo
    @turbo = request.headers["turbo-frame"].present?
  end

  def turbo_render(action, *options)
    render turbo_stream: turbo_stream.send(action, options)
  end

  def include_reserved?
    ENV.fetch("RAILS_SHOW_RESERVED", false) || current_user.try(:member)
  end
end

app/controllers/editor/application_controller.rb
# frozen_string_literal: true

module Editor
  # This controller contain the methods shared for all editor controller
  class ApplicationController < ApplicationController
    before_action :authenticate_editor!

    private

    # deny access unless current_user is an editor
    def authenticate_editor!
      access_denied! unless user_signed_in? && (current_user.editor? || current_user.admin?)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# This helper contain the methods shared for all views
#
# * include Pagy::Frontend
module ApplicationHelper
  # make a div for the font-awesome icons
  def fas_icon(fa_style, span_style: nil, style: false, text: "", tooltip: false)
    # "<span class='icon #{span_style}' #{"style='#{style}'" if style.present?} data-tooltip=\"#{tooltip if tooltip.present?}\" ><i class='fas fa-#{fa_style}' aria-hidden='true'></i></span> #{"<span>#{text}</span>" if text.present?}".html_safe
    tag_i = content_tag(:i, "", class: "fas fa-#{fa_style}", aria: { hidden: "true" })
    span = content_tag(:span, tag_i, class: "icon #{span_style}", style:, data: { tooltip: })
    return span if text.blank?

    span + content_tag(:span, text)
  end

  # Make an html structure for a bulma/awesome icon
  #
  # Example:
  # icon('fas fa-home')
  # `<span class="icon"><i class="fas fa-home"></i></span>`
  #
  # @return [String] bulma / awesome icon structure
  # @param fas [String] class for icon, example: "fas fa-home"
  # @param [Hash] opts to generate content
  # @option opts [String] :class style other "span.icon" class
  def icon(fas, **opts)
    content_tag :span, tag.i(class: fas), class: [ "icon", opts[:class] ]
  end

  # Make an html structure for a bulma/awesome text-icon
  #
  # Example:
  # icon('fas fa-home', 'text')
  # `<span class="text-icon"><span class="icon"><i class="fas fa-home"></i></span><span>text</span></span>`
  #
  # @return [String] bulma / awesome text-icon structure
  # @param [String] fas class for icon, example: "fas fa-home"
  # @param [String] text for the icon
  # @param [Hash] opts to generate content
  # @option opts [String] :class style other "span.icon-text" class
  # @option opts [String] :icon_class style other "span.icon" class
  def icon_text(fas, text, **opts)
    content_tag(
      :span,
      icon(fas, class: opts[:icon_class]) + content_tag(:span, text),
      class: [ "icon-text", opts[:class] ]
    )
  end

  # map of flash and rub notify() for each flash
  def notifications
    flash.to_h.extract!("success", "notice", "warning", "alert").map { |type, text| notify(text, type:) }.join
  end

  # map of status and run notify() for each status
  # @param [Hash] status
  def notify_status(status = {})
    status.map { |k, v| notify(v, type: k) }.join.html_safe if status.present?
  end

  # @param text [String] text of notification
  # @param type [String] type of notification, default: 'alert'
  # @param timeout [String] set the timeout for javascript action, default: 3000
  # @param hidden [Boolean] set visibility class, default true
  # @return [String] Make a div with for the notification
  def notify(text, type: "alert", timeout: 3000, hidden: true)
    content_tag(:div, text.to_s, class: "notification is-#{type} #{'is-hidden' if hidden}",
                                 data: { controller: "noty", noty_type: type, noty_timeout: timeout })
  end

  # generate a list for a select from an enum
  # @param list [Hash], enum option list, default {}
  # @param scope [String] scope of localization, default ''
  # @return [List]
  def t_enum(list = {}, scope = "")
    list.map { |k, _| [ t(k, scope:), k ] }
  end

  # Localize a DateTime with format :long if #obj is present
  # @param [DateTime] obj
  # @return [String] localized and formatted date
  def l_long(obj = nil)
    l(obj, format: :long) if obj.present?
  end

  # Localize a DateTime with format :time if #obj is present
  # @param [DateTime] obj
  # @return [String] localized and formatted date
  def l_time(obj = nil)
    l(obj, format: :time) if obj.present?
  end

  # Localize a DateTime with format :date if #obj is present
  # @param [DateTime,Date] obj
  # @return [String] localized and formatted date
  def l_date(obj = nil)
    l(obj, format: :date) if obj.present?
  end
end

app/views/application/_js_statuses.html.haml
#loader.is-hidden
  .is-loading
#error.modal
  .modal-background
  .modal-content
    .box.has-text-centered
      %i.fas.fa-exclamation-triangle.has-text-danger.fa-4x
      <br/><br/>ATTENZIONE e` stato rilevato un errore di trasmissione, recaricare la pagina e riprovare.
#timeout.modal
  .modal-background
  .modal-content
    .box.has-text-centered
      %i.fas.fa-exclamation-triangle.has-text-danger.fa-4x
      <br/><br/>ATTENZIONE la sessione e` scaduta. Ricaricare la pagina per continuare.

app/views/application/_modal.html.haml
.modal-background
.modal-card.is-xlarge
  %header.modal-card-head
    %p.modal-card-title{ data: { target: 'modal.title' } }
    %p.modal-card-menu{ data: { target: 'modal.menu' } }
    %button.delete{ data: { controller: "modal", action: 'click->modal#close' }, aria: { label: "close" } }
  %section.modal-card-body{ data: { target: 'modal.body' } }= yield
  %section.modal-card-footer{ data: { target: 'modal.footer' } }

app/views/application/_modal_empty.html.haml
%turbo-frame#modal

app/views/application/_nav.html.haml
#nav3.has-background-primary-dark
  .container
    %nav.navbar.has-background-primary-dark{role: 'navigation', aria_label: 'main navigation'}
      .navbar-brand
        %a.navbar-item.has-text-weight-bold.is-italic.is-size-5{href: root_path, data: {turbo_frame: 'yield'}}
          %span.icon
            %i.fas.fa-signature.fa-fw
          %span P
          artecipo
        %a.navbar-burger.burger{role: 'button', aria: {label: 'menu', expanded: 'false'}, data: {action: 'page#toggleMenu'}}
          <span aria-hidden="true"></span><span aria-hidden="true"></span><span aria-hidden="true"></span>
      #nav3-menu.navbar-menu{data: {target: 'page.menu'}}
        .navbar-start
          = link_to fas_icon('calendar', text: 'Eventi'), root_path, class: "navbar-item", data: {turbo_frame: 'yield'}
          = link_to fas_icon('ticket-alt', text: 'Prenotazioni'), tickets_path, class: 'navbar-item', data: {turbo_frame: 'yield'}
        .navbar-end
          .navbar-item.has-dropdown.is-hoverable.has-background-primary-dark
            %a.navbar-link{src: tickets_path}= fas_icon('user', text: current_user.username)
            .navbar-dropdown
              - if current_user.editor?
                %a.navbar-item{ href: editor_root_path, data: {turbo_frame: 'yield'}}= fas_icon('tools', text: 'Gestione eventi')
              -if current_user.admin?
                %a.navbar-item{ href: admin_root_path, data: {turbo_frame: 'yield'}}= fas_icon('users', text: 'Gestione Utenti')
                %a.navbar-item{ href: admin_groups_path, data: {turbo_frame: 'yield'}}= fas_icon('users', text: 'Gestione Gruppi')

              %a.navbar-item{href: destroy_user_session_path, data: {method: :delete}}= fas_icon 'sign-out-alt', text: 'Disconnetti'